schema_version = "1.0.0"

id = "caustics_baking_addon"
version = "3.2.0"
name = "Caustics_Baking"
tagline = "This Addon uses the Cycles Pathracing Engine to do a mixture of Lighttracing and Photon Cashing"
maintainer = "Benary"
type = "add-on"
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]