schema_version = "1.0.0"

id = "caustics_baking_addon"
version = "3.2.1"
name = "Caustics_Baking"
tagline = "Caustics Baking with Cycles"
maintainer = "Benary"
type = "add-on"
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
website = "https://github.com/Orbiter1/Caustics_Baking"